[project]
name = "atp-tennis-dw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "dbt-core>=1.9.4",
  "dbt-duckdb>=1.9.3",
  "dlt[duckdb]>=1.10.0",
  "requests>=2.32.3",
]
